### ISSUE TITLE
Suggestion: When in full screen mode make chat be able to pull down from top or a menu to change colors in full srceen

### ISSUE THREAD

**Issue by Retro-Wave** [sm64js/sm64js#84] opened 2020-11-06 15:51 UTC

**Comment by Kevin-Is-Nice** [comment] 2020-11-10 01:28
**### _y e s_**

**Comment by Whoblue579** [comment] 2020-11-14 21:44
Professional game devs will always tell you gameplay first, then gui, asthetics, and other things

**Comment by Kevin-Is-Nice** [comment] 2020-11-17 14:43
> Professional game devs will always tell you gameplay first, then gui, asthetics, and other things

oh ok so eventually they will do that

**Comment by luphoria** [comment] 2021-05-20 23:23
Duplicate of #19, why did nobody close this previously

**Closed by luphoria** 2021-05-20 23:23 UTC
