### ISSUE TITLE
Mirror room in Castle interior #2 crashes

### ISSUE THREAD

**Issue by RuralAnemone** [sm64js/sm64js#640] opened 2022-02-11 19:00 UTC

**Comment by AgentXLP** [comment] 2022-02-14 22:22
Cannot reproduce this. doesn't crash in either MMO, Vanilla and I even checked 60 FPS. closing for now

**Closed as completed by AgentXLP** 2022-02-14 22:22 UTC

**Comment by RuralAnemone** [comment] 2022-02-15 00:48
okay so this might be because I'm using the effective beta version...? (at https://luphoria.com/sm64js)

[screen recording](https://cdn.ruralanemone.tech/media/screenrec/sm64js.webm)

**Comment by RuralAnemone** [comment] 2022-02-15 00:50
using "crash" lightly

more akin to hardlock, I guess...?

**Comment by AgentXLP** [comment] 2022-03-31 15:02
> okay so this might be because I'm using the effective beta version...? (at https://luphoria.com/sm64js)
> 
> [screen recording](https://cdn.ruralanemone.tech/media/screenrec/sm64js.webm)

Dude that versions over a year old lmfao
