### ISSUE TITLE
A phone adaptation 

### ISSUE THREAD

**Issue by Mloldab** [sm64js/sm64js#291] opened 2021-03-22 20:37 UTC
I liked the thing is that you can play on such but it's not yet adapted is what it will have an update to fit people who will play on phone

**Comment by AgentXLP** [comment] 2021-03-22 23:29
This isn't an issue

**Comment by StyleCannotCodeForShit** [comment] 2021-03-28 23:37
this is for issues, phone support isn't their top priority its mainly getting the game to even work in the first place

**Comment by luphoria** [comment] 2021-04-13 15:36
For future reference: suggestions are welcome here.
Sm64js works on mobile but you have to plug in a keyboard. However i am going to try adding virtual gamepad support. Its long overdue.

**Comment by Someone567123** [comment] 2021-05-02 15:52
ok

**Comment by justabluemouse** [comment] 2021-05-07 00:47
Oh, yeah, a phone adaptation sounds like a great idea!... if your fingers are nimble enough to handle all the controls on the screen size of a Nokia. :trollface: @Mloldab On a serious note, that sounds like a great idea, because it would also mean you'd be able to play sm64js on the go. The only problem is, you'd probably have to connect your phone to a controller or something. There's no way someone would be able to control so many buttons on, like a 5-inch screen. I'm not trying to shoot down your idea, it sounds great, of course, and I'd love it if it was implemented into the game, but that would be the one issue.

**Comment by Someone567123** [comment] 2021-05-07 01:32
:trollface: did it work?

**Comment by justabluemouse** [comment] 2021-05-07 14:46
No, not yet, But maybe it will in the future(though it sounds like hell to try and use touchscreen controls)

**Comment by Someone567123** [comment] 2021-05-08 02:54
nvm

**Comment by luphoria** [comment] 2021-05-20 23:27
Duplicate of #168, sorry i didnt notice this before

**Closed as completed by luphoria** 2021-05-20 23:27 UTC
Labels: enhancement
