### ISSUE TITLE
everytime I try to get in it doesn't load properly

### ISSUE THREAD

**Issue by sme64** [sm64js/sm64js#579] opened 2021-10-26 02:36 UTC
it loads and there's nothing there I try to reload but then there's nothing there again I don't know what's happening there's a bug

**Comment by sme64** [comment] 2021-10-26 02:36
I don't know it's not work

**Comment by luphoria** [comment] 2021-10-26 22:47
Clear your cache, should work

**Comment by luphoria** [comment] 2021-10-26 22:47
Duplicate of #578?

**Closed as completed by luphoria** 2021-10-26 22:47 UTC

**Comment by sme64** [comment] 2021-10-27 02:42
what do you mean by Clear your cache

**Comment by AgentXLP** [comment] 2021-10-31 00:24
```js
Object.keys(window.myMario.skinData).forEach((skinType) => {
        localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
})
```
